# Generated by Django 5.2.6 on 2025-09-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CARs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNO', models.CharField(help_text='Car_id', max_length=255)),
                ('Brand', models.CharField(help_text='Brand Name', max_length=100)),
                ('Model', models.CharField(help_text='Model Number')),
                ('Year', models.CharField(help_text='Release Year', max_length=50)),
                ('Rating', models.DecimalField(decimal_places=1, help_text='Cae Rating (e.g., 8.5)', max_digits=3)),
                ('Color', models.CharField(help_text='Car Outer color')),
            ],
        ),
    ]
